- index.d.ts
- roadmap.md
- src/aggregations/bucket-aggregations/adjacency-matrix-aggregation.js
- src/aggregations/bucket-aggregations/index.js
- src/index.js
- test/aggregations-test/adjacency-matrix-agg.test.js
- test/index.test.js
[Adjacency matrix aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-adjacency-matrix-aggregation.html) was added in elasticsearch 5.3. This PR adds support for the same.
> feat: Add support for Adjacency Matrix Aggregation

- README.md
- docs/documentation.yml
- index.d.ts
- src/core/index.js
- src/core/search-template.js
- src/index.js
- test/core-test/search-template.test.js
- test/index.test.js
Adds a simple helper class for [Search Templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html). Tests and type definitions are also included.
> Add support for Search Template

- src/queries/joining-queries/has-child-query.js
- test/queries-test/has-child-query.test.js
`child_type` field in `has_child` query is deprecated. Change `has_child>child_type` => `has_child>type`.
Closes #13
> Fix deprecation warning for HasChildQuery.type

- src/index.d.ts
- src/queries/term-level-queries/term-query.js
- src/queries/term-level-queries/terms-query.js
- src/queries/term-level-queries/value-term-query-base.js
Support [boolean](https://www.elastic.co/guide/en/elasticsearch/reference/current/boolean.html) values in TermQuery type declarations.
> Add boolean values to type declarations for TermQuery

- .babelrc
In reference to #52 and #45, this adds a single line in the .babelrc to make this usable in browsers.
Closes #45, #52
> Adds browsers: [>1%] to .babelrc

- docs/documentation.yml
- src/aggregations/pipeline-aggregations/bucket-sort-aggregation.js
- src/aggregations/pipeline-aggregations/index.js
- src/index.d.ts
- src/index.js
- test/aggregations-test/bucket-sort-agg.test.js
- test/index.test.js
Adds implementation of Bucket Sort Aggregation https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-sort-aggregation.html
Usage example:
```
const reqBody = esb.requestBodySearch()
.agg(
esb.bucketSortAggregation('sort')
.sort([
esb.sort('user', 'desc')
])
.from(5)
.size(10)
)
);
```
> feat: Implement 'Bucket Sort Aggregation'

- src/core/sort.js
- src/index.d.ts
- test/core-test/sort.test.js
Adds compatibility of new `nested` api for elasticsearch >= 6.1
Removes deprecated `nested_path` and `nested_filter` options.
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/search-request-sort.html#nested-sorting
**WARNING: This is breaking change and this will NOT work with elasticsearch < 6.1**
Usage example:
```
const sort = esb.sort('offer.price', 'asc')
.nested({
path: 'offer',
filter: esb.termQuery('offer.color', 'blue')
});
```
or with old style:
```
const sort = esb.sort('offer.price', 'asc')
.nestedPath('offer')
.nestedFilter(esb.termQuery('offer.color', 'blue'));
```
both examples produce the same output compatible with new elasticsearch api:
```
{
'offer.price': {
order: 'asc',
nested: {
path: 'offer',
filter: {
term: {
'offer.color': 'blue'
}
}
}
}
}
```
> feat: Implement new api for nested sorting for elasticsearch >= 6.1

- src/core/request-body-search.js
- src/index.d.ts
- test/core-test/request-body-search.test.js
Adds support for `track_total_hits` on request body search.
Fixes: #95
> feat: add support for `track_total_hits`

- src/aggregations/bucket-aggregations/composite-agg-values-sources/values-source-base.js
- src/index.d.ts
- test/aggregations-test/composite-agg-values-sources-test/terms-values-source.test.js
Addresses [one of breking change in ES v6.0](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/breaking-changes-6.0.html#_literal_missing_literal_is_deprecated_in_the_literal_composite_literal_aggregation).
This PR adds [CompositeAggregation#missingBucket](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html#_missing_bucket).
> Add CompositeAggregation#missingBucket

- src/index.d.ts
Type for `values` argument in `TermsQuery` is `Array<string|number|boolean>`.
Tested on online builder and all types work fine:
> FIX: termsQuery `values` argument type

- src/aggregations/bucket-aggregations/geo-tile-grid-aggregation.js
- src/aggregations/bucket-aggregations/index.js
- src/index.d.ts
- src/index.js
- test/aggregations-test/geo-tile-grid-agg.test.js
- test/index.test.js
This PR adds support for the [GeoTile Grid Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geotilegrid-aggregation.html) added in ES 7.
> Add GeoTileGridAggregation

- src/aggregations/bucket-aggregations/date-histogram-aggregation.js
- src/index.d.ts
- test/aggregations-test/date-histogram-agg.test.js
Supported from ES 7.2.
Not sure on how to go about 7.x-isms here. Basically, for date histograms the old `interval` is no more (see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html), but elastic-builder supports interval as an explicit function on the aggregation and even as a third optional constructor parameter.
So for 7.x-compatible queries, its necessary to contruct the aggregation with only `name` and `field`, and add the `fixed_interval` via function (see tests).
Also wondering if we should make sure only one of `interval`, `fixed_interval` and `calendar_interval` is being set, since these are mutually exclusive. I am leaning towards "let users shoot themselves in their feet there", as opposed to some magic …
> Added calendar_interval and fixed_interval to date-histogram aggregation

- src/index.d.ts
- src/suggesters/completion-suggester.js
- test/suggesters-test/completion-suggester.test.js
This PR adds support for the [skip_duplicates option of completion suggesters](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#skip_duplicates) added in ES 6.1.
> Add CompletionSuggester.skipDuplicates

- docs/documentation.yml
- src/aggregations/bucket-aggregations/index.js
- src/aggregations/bucket-aggregations/rare-terms-aggregation.js
- src/index.d.ts
- src/index.js
- test/aggregations-test/rare-terms-aggregation.test.js
- test/index.test.js
This PR adds support for the [Rare terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-rare-terms-aggregation.html) added in ES 7.3.
> feat: add RareTermsAggregation

- package.json
- src/aggregations/bucket-aggregations/index.js
- src/aggregations/bucket-aggregations/variable-width-histogram-aggregation.js
- src/index.d.ts
- src/index.js
- test/aggregations-test/variable-width-histogram-aggregation.test.js
- test/index.test.js
This PR makes it possible to use [Variable width histogram aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-variablewidthhistogram-aggregation.html).
Tagging the other co-author: @foxstarius
> feat: Add esb.variableWidthHistogramAggregation

- src/index.d.ts
When type checking in strict mode this line will trigger an error.
```
node_modules/elastic-builder/src/index.d.ts(5122,17): error TS7006: Parameter 'buckets' implicitly has an 'any' type.
```
> fix: parameters type

- src/aggregations/bucket-aggregations/histogram-aggregation-base.js
- src/index.d.ts
- test/aggregations-test/histogram-agg-base.test.js
Fix https://github.com/sudo-suhas/elastic-builder/issues/169
Implements hard_bounds for date histograms, the counterpart of the already existing extended_bounds. 
https://github.com/elastic/elasticsearch/issues/59774 implemented in 7.10
> feat: Add support for date histogram hard_bounds

- src/index.d.ts
- src/index.js
Export `Query` in index.js to allow extensions for special query types that may not be part of the official ES DSL.
We are using this query builder for OpenSearch, where a [new plugin adds the `neural` query](https://opensearch.org/docs/latest/search-plugins/neural-search/). I foresee that the type of queries used in OpenSearch and Elasticsearch will diverge in the future, so it would be nice that we can still use this module as a base to create queries for both. 
There are also other query types used in ES in later versions, which are not commonly used, but can be useful to add yourself like the 
- [Text Expansion query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-text-expansion-query.html)
- [Shape](https://www.elastic.co/guide/en/elasticsearch/reference/cur …
> Make `Query` public to allow custom query extensions

- src/index.d.ts
- src/index.js
- src/queries/specialized-queries/index.js
- src/queries/specialized-queries/script-score-query.js
- test/index.test.js
- test/queries-test/script-score-query.test.js
Adds support for the [`script_score` query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-script-score-query.html) (aka function score 2.0), [added in Elasticsearch 7.0](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/release-highlights-7.0.0.html#_script_score_query_aka_function_score_2_0).
> Add script score query

- src/index.d.ts
- src/index.js
- src/queries/specialized-queries/index.js
- src/queries/specialized-queries/rank-feature-query.js
- test/queries-test/rank-feature.test.js
This adds the rank feature query to elastic-builder, as I'd like to test out rank features to speed up some queries :-)
Closes #192
> Add rank_feature query

- src/index.js
- src/queries/full-text-queries/combined-fields-query.js
- src/queries/full-text-queries/index.js
- test/queries-test/combined-fields-query.test.js
Adds support for the [combined_fields query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-combined-fields-query.html), [added in Elasticsearch 7.13](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/release-notes-7.13.0.html#feature-7.13.0).
> feat: add full-text combined fields query

- .vscode/settings.json
- package.json
- src/core/index.js
- src/core/request-body-search.js
- src/core/runtime-field.js
- src/index.d.ts
- src/index.js
- test/core-test/request-body-search.test.js
- test/core-test/runtime-field.test.js
resolves #152 
Original [PR](https://github.com/sudo-suhas/elastic-builder/pull/165) was raised by @jmaitrehenry but appears to be abandoned. This PR attempts to complete implementation of this feature, based upon his original work.
Add support for Elasticsearch `runtime_mappings` field, added in [v7.11.0](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/release-notes-7.11.0.html).
Usage:
```
const field = esb.runtimeField(
'keyword',
`emit(doc['sessionId'].value + '::' + doc['name'].value)`,
);
const reqBody = esb.requestBodySearch();
reqBody.runtimeMapping('sessionId-eventName', field);
```
Will generate query:
```
{
"runtime_mappings": {
"sessionId-eventName": {
"type": "keyword",
"script": {
"source": "emit(doc['sessionId'].value + '::' + doc['name'].value)"
}
}
}
}
```
- …
> Feat/Add support for runtime_mappings [Issue: #152]

- src/index.d.ts
There was a mismatch between the return types as defined in the JSDoc comments and the implicit return types inferred by TypeScript:
> fix: runtime field class methods return types

- src/core/index.js
- src/core/knn.js
- src/core/request-body-search.js
- src/index.d.ts
- src/index.js
- test/core-test/knn.test.js
- test/core-test/request-body-search.test.js
Add support for knn
https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html
> feat: add knnQuery

- package.json
- src/core/runtime-field.js
- src/index.d.ts
- test/core-test/request-body-search.test.js
- test/core-test/runtime-field.test.js
resolves https://github.com/sudo-suhas/elastic-builder/issues/201
Add support for Elasticsearch lang and params fields in runtime_mappings' script
This Typescript code:
```
const params = {
factor: 2
}
const field = esb.runtimeField("long", "emit(doc['measure'].value * params.factor);")
.lang('painless')
.params(params)
const reqBody = esb.requestBodySearch();
reqBody.runtimeMapping('measure', field);
```
Will generate this query:
```
{
"runtime_mappings": {
"measure": {
"type": "long",
"script": {
"lang": "painless",
"source": "emit(doc['measure'].value * params.factor);",
"params": {
"factor": 2
}
}
}
}
}
```
- Add lang field to RuntimeField
- Add params field to RuntimeField
- Add unit tests
- Make RuntimeField return this to allow calls being chained and to make the it consistent with …
> Runtime field script params

- src/index.d.ts
- test/typedef.test.ts
This PR adds missing TypeScript definitions for `CombinedFieldsQuery` in `src/index.d.ts`. The JavaScript implementation already exists and is exported properly, but TypeScript users were unable to use this query type due to missing type definitions.
- ✨ Added `CombinedFieldsQuery` class definition with all methods and proper typing
- ✨ Added `combinedFieldsQuery` factory function definition  
- ✨ Added comprehensive JSDoc comments with examples
- ✅ Added TypeScript test cases in `test/typedef.test.ts`
```typescript
export class CombinedFieldsQuery extends FullTextQueryBase {
constructor(fields?: string[] | string, queryString?: string);
field(field: string): this;
fields(fields: string[]): this;
autoGenerateSynonymsPhraseQuery(enable: boolean): this;
operator(operator: 'and' | 'or'): …
```
> feat: add TypeScript definitions for CombinedFieldsQuery
